sudo: false
language: go
go:
- "1.10"
services:
- docker
script: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
after_success:
- echo "${GKE_TOKEN}" | base64 -d | docker login -u _json_key --password-stdin "https://${GKE_HOST}"
- docker build -t "${GKE_HOST}/${GKE_PROJECT}/info:master" .
- docker push "${GKE_HOST}/${GKE_PROJECT}/info:master"
