apiVersion: v1
kind: Service
metadata:
  name: info
  namespace: bicycle
spec:
  selector:
    app: info
  ports:
  - port: 80
    name: info
    targetPort: info
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: info
  namespace: bicycle
spec:
  hosts:
  - "*"
  gateways:
  - api-gateway
  http:
  - match:
    - uri:
        prefix: /info
    route:
    - destination:
        port:
          number: 80
        host: info.bicycle.svc.cluster.local
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: info
  namespace: bicycle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: info
        ext: auth
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: info
        image: eu.gcr.io/rso-bicycle/info:master
        imagePullPolicy: Always
        ports:
        - name: info
          containerPort: 8080
        env:
        - name: SERVICE_PORT
          value: "8080"
